apiVersion: v1
kind: ConfigMap
metadata:
  name: wal-service-config
  namespace: wal-service-dev
data:
  # Override DATABASE_HOST to use the correct PostgreSQL service
  DATABASE_HOST: "postgres"
  # Override DATABASE_PORT to ensure it's available
  DATABASE_PORT: "5432"
  # Override DATABASE_NAME to match our dev setup
  DATABASE_NAME: "wal_service"