apiVersion: apps/v1
kind: Deployment
metadata:
  name: wal-service
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: wal-service
        env:
        - name: NODE_ENV
          value: "development"
        - name: DEBUG
          value: "*"
        # Override external service connections for development
        - name: DATABASE_HOST
          value: "host.docker.internal"  # Use host machine's services
        - name: REDIS_HOST
          value: "host.docker.internal"
        - name: KAFKA_BROKERS
          value: "host.docker.internal:9092"
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        - name: debug
          containerPort: 9229
          protocol: TCP
        resources:
          requests:
            memory: "512Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        startupProbe:
          httpGet:
            path: /api/v1/health
            port: http
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 15
        livenessProbe:
          httpGet:
            path: /api/v1/health
            port: http
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /api/v1/health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5