apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: wal-service-base

namespace: wal-service-dev

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - rbac.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
  - poddisruptionbudget.yaml
  - networkpolicy.yaml
  - postgres.yaml
  - redis.yaml
  - kafka.yaml

labels:
- pairs:
    app.kubernetes.io/name: wal-service
    app.kubernetes.io/part-of: wal-service-system

images:
  - name: wal-service
    newTag: latest