apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: wal-service-metrics
  namespace: wal-service
  labels:
    app.kubernetes.io/name: wal-service
    app.kubernetes.io/component: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: wal-service
      app.kubernetes.io/component: api
  endpoints:
  - port: http
    path: /api/v1/metrics
    interval: 30s
    scrapeTimeout: 10s
    honorLabels: true
  namespaceSelector:
    matchNames:
    - wal-service